name: CI Testing
on: 
  push:
    branches:
      - main
jobs:
  run-ci-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install pnpm
        run: npm install -g pnpm
      - name: create env file
        run: |
          touch .env
          echo GOOGLE_DRIVE_CLIENT_ID=${{ secrets.GOOGLE_DRIVE_CLIENT_ID }} >> .env
          echo GOOGLE_DRIVE_CLIENT_SECRET=${{ secrets.GOOGLE_DRIVE_CLIENT_SECRET }} >> .env
          echo GOOGLE_DRIVE_REDIRECT_URI=${{ secrets.GOOGLE_DRIVE_REDIRECT_URI }} >> .env
          echo NANGO_CONFLUENCE_CONNECTION_ID_TEST=${{ secrets.NANGO_CONFLUENCE_CONNECTION_ID_TEST }} >> .env
          echo NANGO_CONNECTION_ID_TEST=${{ secrets.NANGO_CONNECTION_ID_TEST }} >> .env
          echo NANGO_GITHUB_CONNECTION_ID_TEST=${{ secrets.NANGO_GITHUB_CONNECTION_ID_TEST }} >> .env
          echo NANGO_GOOGLE_DRIVE_CONNECTION_ID_TEST=${{ secrets.NANGO_GOOGLE_DRIVE_CONNECTION_ID_TEST }} >> .env
          echo NANGO_JIRA_CONNECTION_ID_TEST=${{ secrets.NANGO_JIRA_CONNECTION_ID_TEST }} >> .env
          echo NANGO_NOTION_CONNECTION_ID_TEST=${{ secrets.NANGO_NOTION_CONNECTION_ID_TEST }} >> .env
          echo NANGO_SALESFORCE_CONNECTION_ID_TEST=${{ secrets.NANGO_SALESFORCE_CONNECTION_ID_TEST }} >> .env
          echo NANGO_SECRET_KEY=${{ secrets.NANGO_SECRET_KEY }} >> .env
          echo SCRAPING_BEE_API_KEY=${{ secrets.SCRAPING_BEE_API_KEY }} >> .env
      - name: Install Dependencies
        run: pnpm install
      - name: Run Tests
        run: pnpm test
